name: Publish new version

on:
  repository_dispatch:
    types: [new-tag-published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_CLONE }}
          
      - name: Set git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Clone project
        run: |
          git clone https://${{ secrets.REPO_CLONE }}@github.com/voiston-ai/voiston-extension
          
      - name: Build project
        env:
          # Pull the secret from GitHub Actions into the runner environment
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
          FEEGOW_TOKEN: ${{ secrets.FEEGOW_TOKEN }}
          SANTA_CRUZ_AUTHORIZATION: ${{ secrets.SANTA_CRUZ_AUTHORIZATION }}
          SANTA_CRUZ_CLIENT: ${{ secrets.SANTA_CRUZ_CLIENT }}
        run: |
          cd voiston-extension/chrome/src
          
          # Configure the scope to point to GitHub Packages
          echo "@voiston-ai:registry=https://npm.pkg.github.com" > .npmrc
          # Pass the authentication token
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          
          npm install
          npm run build
          
      - name: Zip files
        run: |
          cd voiston-extension/chrome/build
          zip -r "build.zip" *

      - name: Commit update
        run: |
          git commit -m "Versão ${{ github.event.client_payload.version }}" --allow-empty
          git push
          
      - name: Publish new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_CLONE }}
        with:
          tag_name: "${{ github.event.client_payload.version }}"
          release_name: "Versão ${{ github.event.client_payload.version }}"
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_CLONE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: voiston-extension/chrome/build/build.zip
          asset_name: "Extensão.Voiston.zip"
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_CLONE }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
